library/urls.py
from django.urls import path

from .views import (
    home, book_list, book_detail, add_book,
    members_list, edit_member, add_member,
    issue_book, issue_detail, import_books,
    top_report,

)

app_name = "library"

urlpatterns = [
    path('', home, name="home"),
    path('books/list/', book_list, name="book_list"),
    path('books/addbook/', add_book, name='add_book'),
    path('members/list/', members_list, name='members_list'),
    path('members/addmember/', add_member, name='add_member'),
    path('books/issue/', issue_book, name='issue_book'),
    path('books/import/', import_books, name='import_books'),
    path('reports/top-report/', top_report, name='top_report'),
    path('books/issue/<id>/', issue_detail, name="issue_detail"),
    path('books/<book_no>/', book_detail, name="book_detail"),
    path('members/<id>/', edit_member, name="edit_member"),
]

# import api patterns
from .api import api_patterns
urlpatterns+=api_patterns

library_management/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('config.urls')),
    path('admin/', admin.site.urls),
    path('home/', include('user.urls')),
    path('library/', include('library.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from .views import (
	home, profile, get_user
	)


app_name = "user"


urlpatterns = [
	path('', home, name="home"),
	path('get_user/', get_user, name="get_user"),
	path('user/<slug:username>', profile, name='profile'),

]

library/forms.py
from django.forms import ModelForm
from .models import (
    Book, Member, BookTransaction,
)

class UpdateBookForm(ModelForm):

    class Meta:
        model = Book
        exclude = ("created_at", "updated_at", "book_no")

class MemberForm(ModelForm):

    class Meta:
        model = Member
        exclude = ("created_at", "updated_at", 'user', 'account_balance')

class BookTransactionForm(ModelForm):

    class Meta:
        model = BookTransaction
        exclude = ("created_at", "updated_at", 'book_no', 'qty',
            'title', 'posting_date', 'docstatus', 'paid', 'type')

library/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import get_user_model
from library_management.utils import (
    qset_list, qset_item, querydb, fetch_frappebooks,
    result_paginator,
)
from .models import (
    Book, BookStockLedger, BookTransaction, BookTransactionHistory,
    Member,
)
from .forms import (
    UpdateBookForm, MemberForm,  BookTransactionForm,
)
# Create your views here.


@login_required
def home(request):
    template_name = 'library/home.html'
    context = {}

    return render(request, template_name, context)

@login_required
def book_list(request):
    template_name = 'library/book/list.html'
    context = {}
    if request.method == 'GET':
        query = request.GET.get('q', '')
        results = Book.objects.filter(
            Q(title__icontains=query)|Q(authors__icontains=query)
        ).order_by('title')
        books = result_paginator(request, results)

        context = {
            'books': books,
            'q': query,
        }
    return render(request, template_name, context)

@login_required
def book_detail(request, book_no):
    template_name = 'library/book/book_detail.html'
    context = {

    }
    try:
        book = Book.objects.get(book_no=book_no)
        context['book'] = book
    except Exception as e:
        print(e)
        context['book'] = None
    # check for POST request
    if(request.method=='POST'):
        if(request.POST):
            print('POST',request.POST, request.FILES)
            # update book
            form = UpdateBookForm(request.POST, request.FILES, instance=context['book'])
            if form.is_valid():
                print('VALID')
                post = form.save(commit=False)
                id = context['book'].id
                post.save()
                context['book'] = post
                print(post)
            else:
                print(form.errors)
        book = qset_item(context['book'])
        return JsonResponse(book, safe=False)
    context['form'] =  UpdateBookForm(instance=context['book'])
    return render(request, template_name, context)

@login_required
def add_book(request):
    template_name = 'library/book/add.html'
    context = {}
    if(request.method=='POST'):
        form = UpdateBookForm(request.POST, request.FILES)
        print(request.POST)
        if(form.is_valid()):
            form.save()
            book = qset_item(Book.objects.get(id=form.instance.pk))
        else:
            book = {}
        return JsonResponse({'book':book}, safe=False)

    return render(request, template_name, context)

@login_required
def issue_book(request):
    template_name = 'library/book/issue_book.html'
    if(request.method=='POST'):
        print(request.POST)
        post = BookTransactionForm(request.POST)
        if(post.is_valid()):
            post.save(commit=False)
            post.instance.qty=1
            post.instance.type='Issued'
            post.instance.docstatus='Draft'
            post.save()
            return JsonResponse(
                {
                    'status':200,
                    'link': f'/library/books/issue/{post.instance.id}/'
                }, safe=False
            )
    context = {
        # 'title': 'Add Member',
        'members': qset_list(Member.objects.all()),
        'books': qset_list(Book.objects.all()),
        'form': BookTransactionForm()
    }

    return render(request, template_name, context)

@login_required
def issue_detail(request, id):
    template_name = 'library/book/issue_detail.html'
    issue = BookTransaction.objects.get(id=id)
    if(request.method=='POST'):
        action = request.POST.get('action')
        if(action=='submit'):
            issue.docstatus = 'Submitted'
            try:
                ledger = BookStockLedger.objects.create(
                    book=issue.book,
                    qty=issue.qty,
                    posting_date=issue.posting_date,
                    type=issue.type,
                    transaction=issue
                )
            except Exception as e:
                pass

        elif(action=='return'):
            issue.type = 'Return'
            try:
                book = Book.objects.get(id=issue.book.id)
                book.balance += 1
                book.save()
            except Exception as e:
                pass

        elif(action=='pay'):
            issue.paid = True
            try:
                member = Member.objects.get(id=issue.member.id)
                member.account_balance -= issue.rental_fee
                member.save()
            except Exception as e:
                pass

        elif(action=='delete'):
            issue.docstatus = 'Submitted'
            issue.delete()
            return JsonResponse({'status':301, 'type':'delete', 'link':'/library/books/list/'})
        else:
            return JsonResponse({'status': 500,})
        issue.save()
        issue = BookTransaction.objects.get(id=id)
        return JsonResponse({
            'status':200, 'type':'refresh',
            'book': qset_item(issue.book),
            'member':qset_item(issue.member),
            'issue': qset_item(issue)
        })

    context = {
        'book': qset_item(issue.book),
        'member':qset_item(issue.member),
        'issue': qset_item(issue)
    }
    return render(request, template_name, context)

# MEMBERS

@login_required
def members_list(request):
    template_name = 'library/members/list.html'
    context = {}
    if request.method == 'GET':
        query = request.GET.get('q', '')
        results = Member.objects.filter(
            name__icontains=query
        ).order_by('name')
        print(results)
        members = result_paginator(request, results)
        context = {

            'members': members,
            'q': query,
        }
    return render(request, template_name, context)


@login_required
def add_member(request):
    template_name = 'library/members/edit.html'
    if(request.method=='POST'):
        post = MemberForm(request.POST, request.FILES)
        if(post.is_valid()):
            post.save()
            return redirect(f'/library/members/{post.instance.id}/')
    context = {
        'title': 'Add Member',
        'form': MemberForm()
    }

    return render(request, template_name, context)

@login_required
def edit_member(request, id):
    template_name = 'library/members/edit.html'
    member = Member.objects.get(id=id)
    if(request.method=='POST'):
        post = MemberForm(request.POST, request.FILES, instance=member)
        if(post.is_valid()):
            post.save()
            member = post.instance

    context = {
        'title': 'Edit Member',
        'member':member,
        'form': MemberForm(instance=member),
        'transactions': BookTransaction.objects.filter(member=member.id).order_by('-id')
    }
    return render(request, template_name, context)

@login_required
def import_books(request):
    template_name = 'library/import/import.html'
    context = {}

    return render(request, template_name, context)


@login_required
def top_report(request):
    template_name = 'library/reports/top_report.html'
    context = {}
    if(request.method=='POST'):
        # TOP CUSTOMERS
        popular_books_query = querydb(
            """
                SELECT b.id, t.title, b.balance, b.qty as total,
                sum(t.qty) as qty, b.book_no
                FROM library_book b
                JOIN library_booktransaction t ON t.book_id=b.id
                WHERE t.docstatus='Submitted'
                GROUP BY t.title, b.id ORDER BY qty DESC
                LIMIT 10
            ;"""
        )
        highest_paying_query = querydb(
            """
                SELECT m.id, m.name, sum(t.rental_fee) as rfee FROM
                library_booktransaction t
                JOIN library_member m ON t.member_id=m.id
                WHERE t.docstatus='Submitted' AND paid=true
                GROUP BY m.id, m.name ORDER BY rfee DESC
                LIMIT 10
            ;"""
        )
        return JsonResponse({
            'popular_books':popular_books_query,
            'highest_paying':highest_paying_query
        }, safe=False)

    return render(request, template_name, context)

library/templates/library/members/add.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}{{member.name}}{% endblock %}
{% block page_name %}{% endblock %}



{% block content %}
<section class="content">
    <div class="card card-default">
      <div class="card-header">
          <h2>Edit Member</h2>
        <h3 class="card-title text-primary">{{member.name|title}}</h3>

        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse">
            <i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" data-card-widget="remove">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <form  id="addupdateform"
            method="POST" enctype="multipart/form-data"
            onsubmit="confirm('Are you sure?')" action=".">
        <div class="row">
          <div class="col-md-8">
            <div class="form-group">
                {% csrf_token %}
              {% bootstrap_form form %}
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
                <img src="{% if member.image %}{{member.image.url}}{% else %}'/static/img/photo2.png'{% endif %}" alt="">
            </div>
          </div>

        </div>
        <!-- /.row -->

        <div class="row">
          <div class="col-md-12">
              <button class="btn btn-primary float-right" type="submit">Submit</button>
          </div>
        </div>
        <!-- /.row -->
        </form>
      </div>
      <!-- /.card-body -->
      <div class="card-footer">
        <!-- Visit <a href="https://select2.github.io/">Select2 documentation</a> for more examples and information about
        the plugin. -->
      </div>
    </div>
</section>
{% endblock %}

{% block scripts %}

{% endblock %}

library/templates/library/members/edit.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}{{member.name}}{% endblock %}
{% block page_name %}{% endblock %}



{% block content %}
<section class="content">
    <div class="card card-default">
      <div class="card-header">
          <h2>{{title}}</h2>
        <h3 class="card-title text-primary">{{member.name|title}}</h3>
        {% if request.path != '/library/members/addmember/' %}
        <a class="btn btn-primary float-right"
        href="/library/books/issue/?member_id={{member.id}}&member_name={{member.name}}">
        Issue Book
        </a>
        {% endif %}

        <!-- <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse">
            <i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" data-card-widget="remove">
            <i class="fas fa-times"></i>
          </button>
        </div> -->
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <form  id="addupdateform"
            method="POST" enctype="multipart/form-data"
            onsubmit="confirm('Are you sure?')" action=".">
        <div class="row">
          <div class="col-md-8">
            <div class="form-group">
                {% csrf_token %}
              {% bootstrap_form form %}
            </div>
          </div>
          {% if request.path != '/library/members/addmember/' %}
          <div class="col-md-4">
            <div class="form-group">
                <img src="{% if member.image %}{{member.image.url}}{% else %}'/static/img/photo2.png'{% endif %}" alt="">
                <hr>
                <span>Account Balance: <span class="text-danger">Rs. {{member.account_balance}}</span></span>
            </div>
          </div>
          {% endif %}

        </div>
        <!-- /.row -->

        <div class="row">
          <div class="col-md-12">
              <button class="btn btn-primary float-right" type="submit">Submit</button>
          </div>
        </div>
        <!-- /.row -->
        </form>
      </div>
{% if request.path != '/library/members/addmember/' %}
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Book Issue Records</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <table id="transaction-table" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>ID</th>
              <th>Book</th>
              <th>Book Bo.</th>
              <th>Date</th>
              <th>Type</th>
              <th>Status</th>
              <th>Fee</th>
              <th>Paid</th>
            </tr>
            </thead>
            <tbody>
            {% for t in transactions %}
            <tr>
              <td><a href="{% url 'library:issue_detail' t.id %}">{{t.id}}</a></td>
              <td>{{t.book}}</td>
              <td>{{t.book_no}}</td>
              <td>{{t.posting_date|date}}</td>
              <td>{{t.type}}</td>
              <td class="text-{% if t.docstatus == 'Draft' %}warning{% else %}primary{% endif %}">{{t.docstatus}}</td>
              <td>{{t.rental_fee}}</td>
              <td class="text-{% if t.paid %}primary{% else %}danger{% endif %}">{{t.paid}}</td>
            </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th>ID</th>
                <th>Book</th>
                <th>Book Bo.</th>
                <th>Date</th>
                <th>Type</th>
                <th>Status</th>
                <th>Fee</th>
                <th>Paid</th>
            </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
    {% endif %}

      <!-- /.card-body -->
      <div class="card-footer">
        <!-- Visit <a href="https://select2.github.io/">Select2 documentation</a> for more examples and information about
        the plugin. -->
      </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
<script>
  $(function () {
      $("#transaction-table").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
        "order": [[ 0, "desc" ]]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');


  });
</script>
{% endblock %}

library/templates/library/members/list.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}Members{% endblock %}
{% block page_name %}Members{% endblock %}



{% block content %}
<section class="content">
  <div class="container-fluid">
      <div class="row">
          <div class="row">
              <!-- <h2 class="text-center display-4">Search</h2> -->
              <div class="card-header">
              <div class="card-tools">
                  <div class="col-md-12 offset-md-2">
                      <form method='GET' action=".">
                          <div class="input-group">
                              <input type="search" class="form-control form-control-lg"
                              placeholder="Search members"
                              value="{{request.GET.q}}" name="q">
                              <div class="input-group-append">
                                  <button type="submit" class="btn btn-lg btn-default">
                                      <i class="fa fa-search"></i>
                                  </button>
                              </div>
                          </div>
                      </form>
                  </div>
              </div>
              <!-- /.card-tools -->
            </div>

          </div>
      </div>
      <!-- <div class="card card-solid"> -->

        <div class="row">
            {% for member in members %}
          <div class="col-md-4">
            <!-- Box Comment -->
            <div class="card card-widget">
              <div class="card-header">
                <div class="user-block">
                  <!-- <img class="img-circle" src="{% static 'static/dist/img/user1-128x128.jpg' %}" alt="User Image"> -->
                  <span class="username"><a href="{% url 'library:edit_member' member.id %}"><h3>{{member.name|title}}</h3></a></span>
                  <span class="description">{{member.member_no}}</span>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <img class="img-fluid pad img-responsive"
                    src="{% if member.image %}{{member.image.url}}{% else %}{% static 'dist/img/user1-128x128.jpg' %}{% endif %}"
                    alt="Photo"
                    style="display: block;
                      margin-left: auto;
                      margin-right: auto;
                      width: 50%;
                      height: 150px">

                <!-- <p>I took this photo this morning. What do you guys think?</p> -->
              </div>
              <!-- /.card-body -->
              <div class="card-footer card-comments">
                <!-- /.card-comment -->
                <div class="card-comment">
                  <!-- User image -->

                  <div class="comment-text">
                    <span class="username">
                      Account Balance - Rs. <b class="text-danger">{{member.account_balance}}</b>
                      <!-- <span class="text-muted float-right"><b>Page(s) - {{member.page}}</b></span> -->
                    </span><!-- /.username -->
                        <!-- {{member.description|truncatechars:150}}... -->
                  </div>
                  <!-- /.comment-text -->
                </div>
                <!-- /.card-comment -->
              </div>

            </div>
            <!-- /.card -->
          </div>
          {% empty %}
          <h1>No member(s) found</h1>
          {% endfor %}
        </div>


        <!-- /.card-body -->
        <div class="row">
          <nav aria-label="Contacts Page Navigation">
            <!-- <ul class="pagination justify-content-center m-0">
              <li class="page-item active"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item"><a class="page-link" href="#">4</a></li>
              <li class="page-item"><a class="page-link" href="#">5</a></li>
              <li class="page-item"><a class="page-link" href="#">6</a></li>
              <li class="page-item"><a class="page-link" href="#">7</a></li>
              <li class="page-item"><a class="page-link" href="#">8</a></li>
              </ul> -->
              {% if members.has_other_pages %}
                <ul class="pagination justify-content-center m-0">
                  {% if members.has_previous %}
                    <li class="page-item"><a class="page-link" href="?q={{q}}&page={{ members.previous_page_number }}">&laquo;</a></li>
                  {% else %}
                    <li class="disabled page-item"><a class="page-link" href="#"><span>&laquo;</span></a></li>
                  {% endif %}
                  {% for i in members.paginator.page_range %}
                    {% if members.number == i %}
                      <li class="active page-item"><a class="page-link" href="#">{{i}}</a><span class="sr-only">(current)</span></li>
                    {% else %}
                      <li class="page-item"><a class="page-link" href="?q={{q}}&page={{ i }}">{{i}}</a></li>
                    {% endif %}
                  {% endfor %}
                  {% if members.has_next %}
                    <li class="page-item"><a class="page-link" href="?q={{q}}&page={{ members.next_page_number }}">&raquo;</a></li>
                  {% else %}
                    <li class="disabled page-item"><a class="page-link" href="#"><span>&raquo;</span></a></li>
                  {% endif %}
                </ul>
              {% endif %}
          </nav>
        </div>
        <!-- /.card-footer -->
      <!-- </div> -->
  </div><!--/. container-fluid -->
</section>
{% endblock %}