config/urls.py
from django.urls import path

from .views import (
    index, guestview
)

app_name = "config"

urlpatterns = [
    path('', index, name="index"),
    path('guest/view/list/', guestview, name="guestview"),
]

library/urls.py
from django.urls import path

from .views import (
    home, book_list, book_detail, add_book,
    members_list, edit_member, add_member,
    issue_book, issue_detail, import_books,
    top_report,

)

app_name = "library"

urlpatterns = [
    path('', home, name="home"),
    path('books/list/', book_list, name="book_list"),
    path('books/addbook/', add_book, name='add_book'),
    path('members/list/', members_list, name='members_list'),
    path('members/addmember/', add_member, name='add_member'),
    path('books/issue/', issue_book, name='issue_book'),
    path('books/import/', import_books, name='import_books'),
    path('reports/top-report/', top_report, name='top_report'),
    path('books/issue/<id>/', issue_detail, name="issue_detail"),
    path('books/<book_no>/', book_detail, name="book_detail"),
    path('members/<id>/', edit_member, name="edit_member"),
]

# import api patterns
from .api import api_patterns
urlpatterns+=api_patterns

library_management/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('config.urls')),
    path('admin/', admin.site.urls),
    path('home/', include('user.urls')),
    path('library/', include('library.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from .views import (
	home, profile, get_user
	)


app_name = "user"


urlpatterns = [
	path('', home, name="home"),
	path('get_user/', get_user, name="get_user"),
	path('user/<slug:username>', profile, name='profile'),

]

config/models.py
from django.db import models
from django.shortcuts import reverse
# from ckeditor_uploader.fields import RichTextUploadingField
# from django_ckeditor_5.fields import CKEditor5Field
from django.utils import timezone

class Setting(models.Model):
    name = models.CharField(max_length=25)
    title = models.CharField(max_length=25)
    email = models.EmailField(max_length=40)
    phone = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=100, blank=True)
    logo = models.ImageField(upload_to='img', blank=True)
    meta_description = models.TextField(blank=True, null=True)



    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse("cp:system_settings", args=[self.pk])

config/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail
from library_management.utils import (
    qset_list, qset_item, querydb, fetch_frappebooks,
    result_paginator,
)
from config.models import Setting
from library.models import Book

# Create your views here.

def guestview(request):
    template_name = 'config/guestview.html'
    context = {}
    if request.method == 'GET':
        query = request.GET.get('q', '')
        results = Book.objects.filter(
            Q(title__icontains=query)|Q(authors__icontains=query)
        ).order_by('title')
        books = result_paginator(request, results)

        context = {
            'books': books,
            'q': query,
        }
    return render(request, template_name, context)

def index(request):
    return redirect('/accounts/login')

# def about(request):
#     template_name = "index/about.html"
#
#     context = {}
#
#     return render(request, template_name, context)

# @csrf_exempt
# def contact(request):
#     template_name = "index/contact.html"
#     context = {}
#     if request.method=="POST":
#         post = request.POST
#         # print(post)
#         # name, email, phone, message = post.values()
#         name, email, phone, message = post.get("name"), post.get("email"), post.get("phone"), post.get("message")
#         print(name, email, phone, message)
#         send_mail(
#             f"{name.title()}",
#             f"{email}<br>{phone}<br>{message}",
#             'no-reply@0.0.0.0:8000',
#             [Setting.objects.get(id=1).email],
#             fail_silently=True,
#         )
#         context['sent'] = True
#
#
#     return render(request, template_name, context)

config/templates/base.html
<!DOCTYPE html>
<html lang="zxx">

<head>
<meta charset="utf-8">
<meta name="description" content="Aila">
<meta name="keywords" content="HTML,CSS,JavaScript">
<meta name="author" content="HiBootstrap">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>{{config.title|title}}</title>
<link rel="icon" href="/static/config/assets/images/tab.png" type="image/png" sizes="16x16">

<link rel="stylesheet" href="/static/config/assets/css/bootstrap.min.css" type="text/css" media="all" />

<link rel="stylesheet" href="/static/config/assets/css/animate.min.css" type="text/css" media="all" />

<link rel="stylesheet" href="/static/config/assets/css/owl.carousel.min.css" type="text/css" media="all" />
<link rel="stylesheet" href="/static/config/assets/css/owl.theme.default.min.css" type="text/css" media="all" />

<link rel="stylesheet" href="/static/config/assets/css/meanmenu.min.css" type="text/css" media="all" />

<link rel="stylesheet" href="/static/config/assets/css/magnific-popup.min.css" type="text/css" media="all" />

<link rel='stylesheet' href='assets/css/boxicons.min.css' type="text/css" media="all" />

<link rel='stylesheet' href='assets/css/line-awesome.min.css' type="text/css" media="all" />

<link rel='stylesheet' href='assets/css/flaticon.css' type="text/css" media="all" />

<link rel="stylesheet" href="/static/config/assets/css/style.css" type="text/css" media="all" />

<link rel="stylesheet" href="/static/config/assets/css/responsive.css" type="text/css" media="all" />
<!--[if IE]>
                <script src="/static/config/http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
            <![endif]-->
</head>
<body>

<div class="preloader orange-gradient">
<div class="preloader-wrapper">
<div class="preloader-grid">
<div class="preloader-grid-item preloader-grid-item-1"></div>
<div class="preloader-grid-item preloader-grid-item-2"></div>
<div class="preloader-grid-item preloader-grid-item-3"></div>
<div class="preloader-grid-item preloader-grid-item-4"></div>
<div class="preloader-grid-item preloader-grid-item-5"></div>
<div class="preloader-grid-item preloader-grid-item-6"></div>
<div class="preloader-grid-item preloader-grid-item-7"></div>
<div class="preloader-grid-item preloader-grid-item-8"></div>
<div class="preloader-grid-item preloader-grid-item-9"></div>
</div>
</div>
</div>


<div class="fixed-top">
<div class="navbar-area">

<div class="mobile-nav">
<a href="/" class="logo">
<img src="/static/config/assets/images/logo.png" alt="logo">
</a>
<div class="navbar-option">
<div class="navbar-option-item dropdown nav-language-option">
<button class="language-option lang-compo dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<img src="/static/config/assets/images/uk.png" alt="flag">
English
</button>
<div class="dropdown-menu language-dropdown-menu" aria-labelledby="dropdownMenuButton1">
<a class="dropdown-item" href="#">
<img src="/static/config/assets/images/uk.png" alt="flag">
English
</a>
<a class="dropdown-item" href="#">
<img src="/static/config/assets/images/germany.png" alt="flag">
Deutsch
</a>
<a class="dropdown-item" href="#">
<img src="/static/config/assets/images/china.png" alt="flag">
简体中文
</a>
<a class="dropdown-item" href="#">
<img src="/static/config/assets/images/arab.png" alt="flag">
العربيّة
</a>
</div>
</div>
<div class="navbar-option-item">
<a href="authentication.html">
<i class="flaticon-login"></i>
</a>
</div>
</div>
</div>

<div class="main-nav main-nav-2">
<div class="container-fluid">
<nav class="navbar navbar-expand-md navbar-light">
<a class="navbar-brand" href="index.html">
<img src="/static/config/assets/images/logo.png" alt="logo">
</a>
<div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
<ul class="navbar-nav mx-auto">
<li class="nav-item">
<a href="/" class="nav-link dropdown-toggle active">Home</a>

</li>
<li class="nav-item">
<a href="/about" class="nav-link">About Us</a>
</li>
<li class="nav-item">
<a href="#" class="nav-link dropdown-toggle">Pages</a>
<ul class="dropdown-menu">
<li class="nav-item">
<a href="faqs.html" class="nav-link">FAQ's</a>
</li>
<li class="nav-item">
<a href="#" class="nav-link dropdown-toggle">Services</a>
<ul class="dropdown-menu">
<li class="nav-item">
<a href="services.html" class="nav-link">Services</a>
</li>
<li class="nav-item">
 <a href="service-details.html" class="nav-link">Service Details</a>
</li>
</ul>
</li>
<li class="nav-item">
<a href="terms-conditions.html" class="nav-link">Terms & Conditions</a>
</li>
<li class="nav-item">
<a href="privacy-policy.html" class="nav-link">Privacy Policy</a>
</li>
<li class="nav-item">
<a href="testimonials.html" class="nav-link">Testimonials</a>
</li>
<li class="nav-item">
<a href="#" class="nav-link dropdown-toggle">User</a>
<ul class="dropdown-menu">
<li class="nav-item">
<a href="authentication.html" class="nav-link">Authentication</a>
</li>
<li class="nav-item">
<a href="forget-password.html" class="nav-link">Forget Password</a>
</li>
</ul>
</li>
<li class="nav-item">
<a href="404.html" class="nav-link">404 Error Page</a>
</li>
</ul>
</li>
<li class="nav-item">
<a href="#" class="nav-link dropdown-toggle">Features</a>
<ul class="dropdown-menu">
<li class="nav-item">
<a href="features.html" class="nav-link">Features</a>
</li>
<li class="nav-item">
<a href="feature-details.html" class="nav-link">Feature Details</a>
</li>
</ul>
</li>
<li class="nav-item">
<a href="pricing.html" class="nav-link">Pricing</a>
</li>
<li class="nav-item">
<a href="#" class="nav-link dropdown-toggle">Blogs</a>
<ul class="dropdown-menu">
<li class="nav-item">
<a href="blogs.html" class="nav-link">Blogs</a>
</li>
<li class="nav-item">
<a href="blog-details.html" class="nav-link">Blog Details</a>
</li>
</ul>
</li>
<li class="nav-item">
<a href="contact-us.html" class="nav-link">Contact Us</a>
</li>
</ul>
 </div>

<div class="navbar-option">

<div class="navbar-option-item">
<a href="/accounts/login" class="btn1 btn-with-image text-nowrap">
<i class="flaticon-login"></i>
<i class="flaticon-login"></i>
Access Account
</a>
</div>
</div>
</nav>
</div>
</div>
</div>
</div>

{% block content %}

{% endblock %}




<footer class="footer-bg">
<div class="container">
<div class="footer-upper">
<div class="row">
<div class="col-sm-12 col-md-12 col-lg-4">
<div class="footer-content-item">
<div class="footer-logo">
<a href="index.html"><img src="/static/config/assets/images/logo-white.png" alt="logo"></a>
</div>
<div class="footer-details">
<p>Lorem ipsum dolor sit amet, consectetur adiisicing elit, sed do eiusmod tempor inc
Neque porro quisquam est qui dolorem aliquam quaerat luptatem. sed do eiusmod tempor
inc </p>
</div>
</div>
</div>
<div class="col-sm-6 col-md-4 col-lg-2">
<div class="footer-content-list footer-content-item">
<div class="footer-content-title">
<h3>Support</h3>
</div>
<ul class="footer-details footer-list">
<li><a href="faqs.html">FAQ's</a></li>
<li><a href="privacy-policy.html">Privacy Policy</a></li>
<li><a href="terms-conditions.html">Terms & Conditions</a></li>
<li><a href="blogs.html">Blogs</a></li>
<li><a href="contact-us.html">Contact Us</a></li>
</ul>
</div>
</div>
<div class="col-sm-6 col-md-4 col-lg-2">
<div class="footer-content-list footer-content-item">
<div class="footer-content-title">
<h3>Company</h3>
</div>
<ul class="footer-details footer-list">
<li><a href="about-us.html">About Us</a></li>
<li><a href="services.html">Services</a></li>
<li><a href="features.html">Features</a></li>
<li><a href="pricing.html">Our Pricing</a></li>
<li><a href="blogs.html">Blogs</a></li>
</ul>
</div>
</div>
<div class="col-sm-6 col-md-4 col-lg-4">
<div class="footer-content-list footer-content-item">
<div class="footer-content-title">
<h3>Address</h3>
</div>
<ul class="footer-details footer-list">
<li>Address: <span>456 Labisto Parkways, CA, United States</span></li>
<li>Message: <span><a href="https://templates.hibootstrap.com/cdn-cgi/l/email-protection#4c25222a230c2d20252d622f2321"><span class="__cf_email__" data-cfemail="92fbfcf4fdd2f3fefbf3bcf1fdff">[email&#160;protected]</span></a></span></li>
<li>Phone: <span><a href="tel:(+00)67834598">(+00) 678 345 98</a></span></li>
<li>Faq: <span>+(456) 332-897-234</span></li>
</ul>
</div>
</div>
</div>
</div>
<div class="footer-lower">
<div class="footer-lower-item footer-copyright-text">
<p>Copyright ©2021 Design & Developed by <a href="https://hibootstrap.com/" target="_blank">HiBootstrap</a></p>
</div>
<div class="footer-lower-item footer-social-logo">
<ul class="footer-social-list">
 <li class="social-btn social-btn-fb"><a href="#"><i class='bx bxl-facebook'></i></a></li>
<li class="social-btn social-btn-tw"><a href="#"><i class='bx bxl-twitter'></i></a></li>
<li class="social-btn social-btn-ins"><a href="#"><i class='bx bxl-instagram'></i></a></li>
<li class="social-btn social-btn-pin"><a href="#"><i class='bx bxl-pinterest-alt'></i></a></li>
<li class="social-btn social-btn-yt"><a href="#"><i class='bx bxl-youtube'></i></a></li>
</ul>
</div>
</div>
</div>
</footer>


<script data-cfasync="false" src="/static/config/https://templates.hibootstrap.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="/static/config/assets/js/jquery-3.5.1.min.js"></script>
<script src="/static/config/assets/js/bootstrap.bundle.min.js"></script>

<script src="/static/config/assets/js/jquery.magnific-popup.min.js"></script>

<script src="/static/config/assets/js/owl.carousel.min.js"></script>

<script src="/static/config/assets/js/jquery.ajaxchimp.min.js"></script>

<script src="/static/config/assets/js/form-validator.min.js"></script>

<script src="/static/config/assets/js/contact-form-script.js"></script>

<script src="/static/config/assets/js/jquery.meanmenu.min.js"></script>

<script src="/static/config/assets/js/jquery.waypoints.js"></script>

<script src="/static/config/assets/js/counter-up.js"></script>

<script src="/static/config/assets/js/script.js"></script>
</body>

</html>

config/templates/guestview.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Books</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/dist/css/adminlte.min.css">
</head>
<body class="hold-transition lockscreen">

            <section class="content">
              <div class="container-fluid">
                      <div class="row">
                          <!-- <h2 class="text-center display-4">Search</h2> -->
                          <div class="card-header">
                          <div class="card-tools">
                              <div class="col-md-12 offset-md-2">
                                  <form method='GET' action=".">
                                      <div class="input-group">
                                          <input type="search" class="form-control form-control-lg"
                                          placeholder="Search books"
                                          value="{{request.GET.q}}" name="q">
                                          <div class="input-group-append">
                                              <button type="submit" class="btn btn-lg btn-default">
                                                  <i class="fa fa-search"></i>
                                              </button>
                                          </div>
                                      </div>
                                  </form>
                              </div>
                          </div>
                          <!-- /.card-tools -->
                        </div>

                      </div>
                  <!-- <div class="card card-solid"> -->

                    <div class="row">
                        {% for book in books %}
                      <div class="col-md-4">
                        <!-- Box Comment -->
                        <div class="card card-widget">
                          <div class="card-header">
                              <div class="row">
                                  <div class="user-block text-primary">
                                      <!-- <img class="img-circle" src="{% static 'static/dist/img/user1-128x128.jpg' %}" alt="User Image"> -->
                                      <span class="username"><a href="{% url 'library:book_detail' book.book_no %}"><h5>{{book.title|truncatechars:40}}</h5></a></span>
                                  </div>
                              </div>
                            <div class="row">
                                <span class="col-md-6 float-left">#{{book.book_no}}</span>
                                <span class="col-md-6 float-right">Bal Qty. {{book.balance}}</span>

                            </div>
                          </div>
                          <!-- /.card-header -->
                          <div class="card-body">
                            <img class="img-fluid pad img-responsive"
                                src="{% if book.image %}{{book.image.url}}{% else %}{% static 'img/book.jpeg' %}{% endif %}"
                                alt="Photo"
                                style="display: block;
                                  margin-left: auto;
                                  margin-right: auto;
                                  width: 50%;
                                  height: 150px">

                            <!-- <p>I took this photo this morning. What do you guys think?</p> -->
                          </div>
                          <!-- /.card-body -->
                          <div class="card-footer card-comments">
                            <!-- /.card-comment -->
                            <div class="card-comment">
                              <!-- User image -->

                              <div class="comment-text">
                                <span class="username">
                                  ISBN - <b>{{book.isbn}}</b>
                                  <span class="text-muted float-right"><b>Page(s) - {{book.page}}</b></span>
                                </span><!-- /.username -->
                                {% if book.description %}
                                    {{book.description|truncatechars:150}}...
                                {% endif %}
                              </div>
                              <!-- /.comment-text -->
                            </div>
                            <!-- /.card-comment -->
                          </div>

                        </div>
                        <!-- /.card -->
                      </div>
                      {% empty %}
                      <h1>No book found</h1>
                      {% endfor %}
                    </div>


                    <!-- /.card-body -->
                    <div class="row">
                      <nav aria-label="Contacts Page Navigation">
                        <!-- <ul class="pagination justify-content-center m-0">
                          <li class="page-item active"><a class="page-link" href="#">1</a></li>
                          <li class="page-item"><a class="page-link" href="#">2</a></li>
                          <li class="page-item"><a class="page-link" href="#">3</a></li>
                          <li class="page-item"><a class="page-link" href="#">4</a></li>
                          <li class="page-item"><a class="page-link" href="#">5</a></li>
                          <li class="page-item"><a class="page-link" href="#">6</a></li>
                          <li class="page-item"><a class="page-link" href="#">7</a></li>
                          <li class="page-item"><a class="page-link" href="#">8</a></li>
                          </ul> -->
                          {% if books.has_other_pages %}
                            <ul class="pagination justify-content-center m-0">
                              {% if books.has_previous %}
                                <li class="page-item"><a class="page-link" href="?q={{q}}&page={{ books.previous_page_number }}">&laquo;</a></li>
                              {% else %}
                                <li class="disabled page-item"><a class="page-link" href="#"><span>&laquo;</span></a></li>
                              {% endif %}
                              {% for i in books.paginator.page_range %}
                                {% if books.number == i %}
                                  <li class="active page-item"><a class="page-link" href="#">{{i}}</a><span class="sr-only">(current)</span></li>
                                {% else %}
                                  <li class="page-item"><a class="page-link" href="?q={{q}}&page={{ i }}">{{i}}</a></li>
                                {% endif %}
                              {% endfor %}
                              {% if books.has_next %}
                                <li class="page-item"><a class="page-link" href="?q={{q}}&page={{ books.next_page_number }}">&raquo;</a></li>
                              {% else %}
                                <li class="disabled page-item"><a class="page-link" href="#"><span>&raquo;</span></a></li>
                              {% endif %}
                            </ul>
                          {% endif %}
                      </nav>
                    </div>
                    <!-- /.card-footer -->
                  <!-- </div> -->
              </div><!--/. container-fluid -->
            </section>

<!-- jQuery -->
<script src="/static/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>